-- local eslint = {
--   -- formatting and linting to respect project settings
--   -- Only run when config exists
--   condition = function(ctx)
--     return vim.fs.find({
--       ".eslintrc",
--       ".eslintrc.js",
--       ".eslintrc.json",
--       ".eslintrc.yaml",
--       ".eslintrc.yml",
--       "eslint.config.js",
--     }, { path = ctx.filename, upward = true })[1] ~= nil
--   end,
-- }

-- local eslint = {
--   rules = {
--     ["@typescript-eslint/no-unsafe-assignment"] = "off",
--     ["@typescript-eslint/no-unsafe-member-access"] = "off",
--     ["@typescript-eslint/no-unsafe-call"] = "off",
--     ["@typescript-eslint/no-unsafe-return"] = "off",
--   },
-- }
-- return {
-- "mfussenegger/nvim-lint",
-- opts = {
-- Configure ESLint to use project config
-- linters = {
-- eslint = eslint,
-- },
-- },
-- }
return {}
