-- docs: https://github.com/folke/zen-mode.nvim
-- return {
--   'folke/zen-mode.nvim',
--   cmd = 'ZenMode',
--   opts = {
--     window = {
--       width = 0.55,
--     },
--     plugins = {
--       options = {
--         enabled = true,
--         ruler = false, -- disables the ruler text in the cmd line area
--         showcmd = true, -- enables the command in the last line of the screen
--       },
--     },
--   },
--   keys = { { '<leader>tz', '<cmd>ZenMode<cr>', desc = 'Toggle Zen Mode' } },
-- }
-- this is now handled by snacks.lua
return {}
